apiVersion: v1
kind: ConfigMap
metadata:
  name: __PROJECT_SLUG__-config
data:
  DJANGO_SETTINGS_MODULE: config.settings.prod
  APP_ENV: production
  SERVICE_NAME: __SERVICE_NAME__
  PORT: "__PORT__"
  LOG_LEVEL: INFO
  JSON_LOGS: "true"
  DJANGO_ALLOWED_HOSTS: .example.com
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/__PROJECT_SLUG__
  DB_CONN_MAX_AGE: "60"
  DB_CONN_HEALTH_CHECKS: "true"
  DB_CONNECT_TIMEOUT_SECONDS: "5"
  DB_STATEMENT_TIMEOUT_MS: "0"
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  CELERY_CONCURRENCY: "2"
  CELERY_MAX_TASKS_PER_CHILD: "1000"
  CELERY_TASK_SOFT_TIME_LIMIT_SECONDS: "300"
  CELERY_TASK_TIME_LIMIT_SECONDS: "360"
  READINESS_CHECK_REDIS: "true"
  READINESS_REDIS_TIMEOUT_SECONDS: "2"
  GUNICORN_WORKERS: "3"
  GUNICORN_WORKER_CLASS: sync
  GUNICORN_THREADS: "1"
  GUNICORN_WORKER_TMP_DIR: /dev/shm
  GUNICORN_KEEPALIVE: "5"
  GUNICORN_TIMEOUT: "30"
  GUNICORN_GRACEFUL_TIMEOUT: "30"
  GUNICORN_MAX_REQUESTS: "1000"
  GUNICORN_MAX_REQUESTS_JITTER: "100"
