apiVersion: apps/v1
kind: Deployment
metadata:
  name: __PROJECT_SLUG__-beat
  labels:
    app.kubernetes.io/name: __PROJECT_SLUG__
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: __PROJECT_SLUG__
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: __PROJECT_SLUG__
        app.kubernetes.io/component: beat
    spec:
      terminationGracePeriodSeconds: 45
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: beat
          image: ghcr.io/__OWNER__/__PROJECT_SLUG__:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command: ["celery", "-A", "config", "beat", "-l", "INFO"]
          envFrom:
            - configMapRef:
                name: __PROJECT_SLUG__-config
            - secretRef:
                name: __PROJECT_SLUG__-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
