apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __PROJECT_SLUG__-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: __PROJECT_SLUG__-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: __PROJECT_SLUG__-web
                port:
                  number: 80
