apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: __PROJECT_SLUG__-async
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: ["worker", "beat"]
      - key: app.kubernetes.io/name
        operator: In
        values: ["__PROJECT_SLUG__"]
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
