apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: __PROJECT_SLUG__-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: __PROJECT_SLUG__
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: __PORT__
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
