apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: __PROJECT_SLUG__-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: __PROJECT_SLUG__
      app.kubernetes.io/component: web
